# Generated by Django 4.2.7 on 2023-12-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_clientplans_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VWrfRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('site_type', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.TextField(blank=True, null=True)),
                ('temp_c', models.FloatField(blank=True, null=True)),
                ('wind_speed_10m_mps', models.FloatField(blank=True, null=True)),
                ('wind_direction_in_deg', models.FloatField(blank=True, null=True)),
                ('swdown_wpm2', models.FloatField(blank=True, null=True)),
                ('swdown2_wpm2', models.FloatField(blank=True, null=True)),
                ('clearsky_wpm2', models.FloatField(blank=True, null=True)),
                ('rain', models.FloatField(blank=True, null=True)),
                ('cloud_index', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'v_wrf_revision',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VWrfData',
            fields=[
                ('site_name', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('site_type', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('timezone', models.TextField(blank=True, null=True)),
                ('temp_c', models.FloatField(blank=True, null=True)),
                ('wind_speed_10m_mps', models.FloatField(blank=True, null=True)),
                ('wind_direction_in_deg', models.FloatField(blank=True, null=True)),
                ('swdown_wpm2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'v_wrf_data',
                'unique_together': {('timestamp', 'site_name')},
            },
        ),
    ]
